=== nbezalwar/globalsca/globallink/globalLinkContentMonitor.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:complexType name="providerType">
		<xs:annotation>
			<xs:documentation>An provider that returns certain items for a catalog.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="bean" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The name of an existing bean that implements the CatalogContentProvider interface.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="contentType">
		<xs:sequence>
			<xs:element name="provider" type="providerType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" use="required">
			<xs:annotation>
				<xs:documentation>The name of an existing bean that implements the CatalogContentProvider interface.</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:ID">
					<xs:pattern value="[a-zA-Z]+" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="scanType">
		<xs:annotation>
			<xs:documentation>Configuration for a specific scan of a CatalogVersion.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="content" type="xs:IDREF" use="required">
			<xs:annotation>
				<xs:documentation>The ID of some content.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="source" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The ISO code defined in Hybris for the source language of the submission</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="target" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>A comma separated list of ISO codes defined in Hybris for the target languages of the submission</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="project" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The Project Director shortcode of the project of the submission</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="catalogType">
		<xs:annotation>
			<xs:documentation>Defines a CatalogVersion to be monitored.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="scan" type="scanType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The ID of the catalog.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="version" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>The Version of the CatalogVersion.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	
	<xs:element name="contentMonitor">
		<xs:annotation>
			<xs:documentation>The root element of the content monitor configuration file.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="content" type="contentType" minOccurs="1" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Defines collections of items.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="catalog" type="catalogType" minOccurs="1" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Defines collections of items.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="schemaVersion" type="xs:integer" use="required">
				<xs:annotation>
					<xs:documentation>The schema version this configuration is based on.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== nbezalwar/globalsca/globalsca/globalLinkContentMonitor.xml
<?xml version="1.0" encoding="UTF-8"?>
<contentMonitor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="globalLinkContentMonitor.xsd" schemaVersion="1">
  <content id="inco">
    <provider bean="scaIncoProductProvider" />
    <provider bean="scaIncoProductBenefitProvider" />
    <provider bean="scaIncoGlobalCategoryProvider" />
    <provider bean="scaIncoFinderCategoryProvider" />
    <provider bean="scaTargetGroupQuestionnaireTextProvider" />
  </content>
  <content id="afh">
    <provider bean="scaScaProductProvider" />
    <provider bean="scaScaGlobalCategoryProvider" />
    <provider bean="scaEnvInfoTextBlockProvider" />
  </content>
	<!--
		Master catalog for testing purposes only
	-->
  <catalog id="Inco_central" version="Online">
    <scan content="inco" project="HYB000001" source="en" target="sv-SE" />
  </catalog>
  <catalog id="SE_local" version="Online">
    <scan content="inco" project="HYB000001" source="en" target="sv-SE" />
    <scan content="afh" project="HYB000001" source="en" target="sv-SE" />
  </catalog>
  <catalog id="BE_local" version="Online">
    <scan content="inco" project="HYB000001" source="en" target="fr-BE,nl-BE" />
  </catalog>
  <catalog id="DK_local" version="Online">
    <scan content="afh" project="HYB000001" source="en" target="da-DK" />
  </catalog>
</contentMonitor>
